# Generated by Django 3.0 on 2019-12-17 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999)], verbose_name='銘柄コード')),
                ('price', models.FloatField(verbose_name='登録時株価')),
                ('memo', models.TextField(verbose_name='備考')),
            ],
        ),
    ]
